### ISSUE TITLE
Binay profile

### ISSUE THREAD

**Issue by agarwalBinay18** [casbin/Talent2021#2]
I am Binay Agarwal, an undergraduate Computer science and engineering student from India. I am personally familiar with Golang, Java, C++, React, and NodeJs. I have well-known knowledge of the backend. I use Java and C++ for development; I have a well-known knowledge of open-source contribution, Also, I had contributed to some past projects in other organizations and I hope to participate in the development of the Casbin project.

**Comment by hsluoyz** [comment]
Thank you for your interest in Casbin. We are currently recruiting student candidates for Gsoc2021. If you are interested in casbin, you can actively participate in it. First, start with solving some issues in the community, submit some pr, so that the community can see your strength, and then a mentor will contact you.
